# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9eb4be9df435f8e725f84dc287c1c2c2c7ff84281e651a4b5a6224b1cfc6641793c4c92979063aac9c3234dda621ada01ee9843b0bb97151803e07003237860

test:
  secret_key_base: f0896825477182ba10f0155c2ab25afe0f8b64cba64c76015c6ce18e99e14f74b2247d4a497b6560df72f298b7504e9cc91749b82bab3e39a30846cfd730543a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
